### ISSUE TITLE
Customize PORT

### ISSUE THREAD

**Issue by danilofuchs** [wiremock/wiremock-docker#47]
How do I customize the server PORT in docker-compose?

I tried setting `PORT=8181` env but it had no affect.

**Comment by danilofuchs** [comment]
I discovered it is possible to customize flags during entrypoint

```
entrypoint: ["/docker-entrypoint.sh", "--port=8181"]
```

**Comment by rodolpheche** [comment]
It's effectively described in the doc : https://github.com/wiremock/wiremock-docker#start-a-wiremock-container-with-wiremock-arguments

However, I'm aware that it doesn't explain how to use it with docker-compose because I don't want to increase the doc with all orchestrators syntax (docker-compose, k8s, ...) in order to keep it clear

Finally, I recommand to not use the entrypoint for giving arguments. Prefer using the command that only needs to provide args:
```yaml
command: ["--port=8181"]
```
